DROP DATABASE IF EXISTS DB_LOGIN_MAGICTG;
CREATE DATABASE DB_LOGIN_MAGICTG;

USE DB_LOGIN_MAGICTG;

DROP TABLE IF EXISTS T_LOGIN;
CREATE TABLE T_LOGIN(
	ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_USUARIO VARCHAR(20) NOT NULL,
    PASSWORD_USUARIO VARCHAR(30) NOT NULL
);

