DROP DATABASE IF EXISTS DB_MAGICTG;
CREATE DATABASE DB_MAGICTG;

USE DB_MAGICTG;

DROP TABLE IF EXISTS T_CARDS;
CREATE TABLE T_CARDS(
	ID_CARD INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(255) NOT NULL,
    MANA_COST VARCHAR(255) NOT NULL,
    CMC INT NOT NULL,
    COLOR VARCHAR(255) NOT NULL,
    COLOR_IDENTITY VARCHAR(255) NOT NULL,
    PODER INT NOT NULL,
    RESISTENCIA INT NOT NULL,
    TIPO INT NOT NULL,
    RAREZA INT NOT NULL,
    CARD_SET INT NOT NULL,
    PRECIO FLOAT
);

DROP TABLE IF EXISTS T_RAREZA;
CREATE TABLE T_RAREZA(
	ID_RAREZA INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_RAREZA VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS T_SET;
CREATE TABLE T_SET(
	ID_SET  INT AUTO_INCREMENT PRIMARY KEY,
    SET_NAME VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS T_TYPE;
CREATE TABLE T_TYPE(
	ID_TYPE INT AUTO_INCREMENT PRIMARY KEY,
    TYPE_NAME VARCHAR(255) NOT NULL
);


ALTER TABLE T_CARDS ADD CONSTRAINT FK_CARD_RARITY FOREIGN KEY (RAREZA) REFERENCES T_RAREZA(ID_RAREZA);
ALTER TABLE T_CARDS ADD CONSTRAINT FK_CARD_SET FOREIGN KEY (CARD_SET) REFERENCES T_SET(ID_SET);
ALTER TABLE T_CARDS ADD CONSTRAINT FK_CARD_TYPE FOREIGN KEY (TIPO) REFERENCES T_TYPE(ID_TYPE);
